FROM golang:1.23 as base

WORKDIR /app
FROM base as dev
ENV GOCACHE=/tmp/go-cache
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
CMD ["air"]